name: Compilar DBZ Story Editor a EXE

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Obtener código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias y PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compilar ejecutable (.exe)
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "DBZ_Story_Editor" "DBZ_STORY_EDITOR_DLC EDITION_2.py"

    - name: Subir ejecutable compilado como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: DBZ_Story_Editor_EXE
        path: dist/DBZ_Story_Editor/
